<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Verstack.App</RootNamespace>
        <AssemblyName>Verstack</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Verstack.Bootstrap\Verstack.Bootstrap.csproj" />
        <ProjectReference Include="..\Verstack.ECS\Verstack.ECS.csproj" />
        <ProjectReference Include="..\Verstack.Network\Verstack.Network.csproj"/>
    </ItemGroup>

</Project>