<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\engine\Verstack.Engine.Ecs\Verstack.Engine.Ecs.csproj" />
      <ProjectReference Include="..\..\shared\Verstack.Shared.Maths\Verstack.Shared.Maths.csproj" />
      <ProjectReference Include="..\..\shared\Verstack.Shared.Spatial\Verstack.Shared.Spatial.csproj" />
      <ProjectReference Include="..\..\shared\Verstack.Shared.Voxel\Verstack.Shared.Voxel.csproj" />
      <ProjectReference Include="..\Verstack.Layers.Global\Verstack.Layers.Global.csproj" />
    </ItemGroup>

</Project>
