<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Pipelines.Sockets.Unofficial" Version="2.3.1"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Verstack.Debug\Verstack.Debug.csproj" />
      <ProjectReference Include="..\Verstack.ECS\Verstack.ECS.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Verstack.Network.Benchmark" />
        <InternalsVisibleTo Include="Verstack.Network.Tests" />
    </ItemGroup>
    
</Project>