<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Verstack.Layer.Realm\Verstack.Layer.Realm.csproj" />
        <ProjectReference Include="..\Verstack.Nbt\Verstack.Nbt.csproj" />
        <ProjectReference Include="..\Verstack.ECS\Verstack.ECS.csproj" />
        <ProjectReference Include="..\Verstack.Lifecycle\Verstack.Lifecycle.csproj" />
        <ProjectReference Include="..\Verstack.Network\Verstack.Network.csproj" />
        <ProjectReference Include="..\Verstack.Layer.Global\Verstack.Layer.Global.csproj" />
    </ItemGroup>

</Project>
