<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\engine\Verstack.Engine.Bridge\Verstack.Engine.Bridge.csproj" />
      <ProjectReference Include="..\..\engine\Verstack.Engine.Ecs\Verstack.Engine.Ecs.csproj" />
      <ProjectReference Include="..\..\engine\Verstack.Engine.Lifecycle\Verstack.Engine.Lifecycle.csproj" />
      <ProjectReference Include="..\..\engine\Verstack.Engine.Network\Verstack.Engine.Network.csproj" />
      <ProjectReference Include="..\..\shared\Verstack.Shared.Assets\Verstack.Shared.Assets.csproj" />
      <ProjectReference Include="..\..\shared\Verstack.Shared.Nbt\Verstack.Shared.Nbt.csproj" />
      <ProjectReference Include="..\Verstack.Layers.Global\Verstack.Layers.Global.csproj" />
    </ItemGroup>

</Project>
