<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\shared\Verstack.Shared.Debug\Verstack.Shared.Debug.csproj" />
      <ProjectReference Include="..\Verstack.Engine.Ecs\Verstack.Engine.Ecs.csproj" />
      <ProjectReference Include="..\Verstack.Engine.Network\Verstack.Engine.Network.csproj" />
    </ItemGroup>

</Project>
